language: python
python:
  - "3.7"
before_install:
  - sudo apt-get -y install whois
install:
  - pip install -e . 
  - pip install asynctest pytest-cov codecov
script:
  - pytest --cov=asyncwhois
after_success:
  - codecov
